[tool.poetry]
name = "real-time-visuals"
version = "0.1.0"
description = ""
authors = ["trandon <163871797+x0trandon@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
